/* The exercise database.
 *
 * One entry per exercise. To add one, copy a similar entry and change it.
 *   motion     which movement from motions.js drives the 3D body (opts tweak it)
 *   load       what the body holds: bodyweight, dumbbells, goblet, kettlebell, barbell, barbellBack, band
 *   muscles    prime movers (glow orange), secondary (glow softer)
 *   camera     side, back, front, three (3/4 front), threeBack, low
 *   faultCamera  optional camera for the right-vs-wrong split, when the fault is hidden from the normal view
 *   fault      optional right-vs-wrong demo: knees_cave, heels_lift, back_round, hips_sag, arch_back, lean_back
 *   where      home, gym or both
 */
window.EXERCISES = [
  // ---------------- LEGS ----------------
  { id: 'bodyweight-squat', name: 'Bodyweight squat', motion: 'squat', opts: { arms: 'forward' }, load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'abs'], camera: 'side', fault: 'knees_cave', equipment: [], sets: '3 x 12',
    cues: ['sit back and down like there is a chair behind you', 'keep your whole foot on the floor', 'push the floor away to stand'],
    mistakes: ['Knees falling in', 'Heels lifting', 'Chest collapsing forward'] },
  { id: 'goblet-squat', name: 'Goblet squat', motion: 'squat', opts: { arms: 'goblet' }, load: 'goblet', area: 'Legs', where: 'both', level: 1,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'abs', 'upper_back'], camera: 'side', fault: 'heels_lift', equipment: ['Dumbbell'], sets: '3 x 10',
    cues: ['hold the weight tight to your chest', 'elbows inside your knees at the bottom', 'drive up through your heels'],
    mistakes: ['Heels lifting', 'Weight drifting away from the chest', 'Cutting depth short'] },
  { id: 'barbell-back-squat', name: 'Barbell back squat', motion: 'squat', opts: { arms: 'backbar' }, load: 'barbellBack', area: 'Legs', where: 'gym', level: 3,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'lower_back', 'abs'], camera: 'threeBack', fault: 'knees_cave', equipment: ['Barbell', 'Squat rack'], sets: '4 x 6',
    cues: ['brace like someone is about to poke your stomach', 'knees follow your toes', 'stand up with the bar and your hips together'],
    mistakes: ['Knees caving', 'Hips shooting up first', 'Losing the brace at the bottom'] },
  { id: 'sumo-squat', name: 'Dumbbell sumo squat', motion: 'squat', opts: { arms: 'hang', sumo: true }, load: 'dumbbellCenter', area: 'Legs', where: 'both', level: 1,
    muscles: ['adductors', 'glutes', 'quads'], secondary: ['abs'], camera: 'front', fault: 'knees_cave', equipment: ['Dumbbell'], sets: '3 x 12',
    cues: ['wide stance, toes turned out', 'push your knees out over your toes', 'stay tall as you sink'],
    mistakes: ['Knees falling in', 'Leaning forward'] },
  { id: 'wall-sit', name: 'Wall sit', motion: 'wallSit', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['quads'], secondary: ['glutes'], camera: 'side', equipment: ['Wall'], sets: '3 x 30 sec',
    cues: ['back flat on the wall', 'knees over ankles', 'breathe slowly and hold'],
    mistakes: ['Knees drifting past the toes', 'Holding your breath'] },
  { id: 'sit-to-stand', name: 'Sit to stand', motion: 'sitToStand', load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['quads', 'glutes'], secondary: ['abs'], camera: 'side', fault: 'knees_cave', equipment: ['Chair'], sets: '3 x 10',
    cues: ['nose over toes to stand up', 'no hands if you can', 'sit down slowly, do not flop'],
    mistakes: ['Using the hands to push up', 'Dropping into the chair', 'Knees falling in'] },
  { id: 'split-squat', name: 'Split squat', motion: 'splitSquat', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'hip_flexors'], camera: 'side', fault: 'knees_cave', equipment: [], sets: '3 x 8 each side',
    cues: ['drop the back knee straight down', 'front foot stays flat', 'stay tall through the chest'],
    mistakes: ['Front knee caving in', 'Front heel lifting', 'Stance too narrow'] },
  { id: 'db-split-squat', name: 'Dumbbell split squat', motion: 'splitSquat', opts: { dumbbells: true }, load: 'dumbbells', area: 'Legs', where: 'both', level: 2,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'forearms'], camera: 'side', fault: 'knees_cave', equipment: ['Dumbbells'], sets: '3 x 8 each side',
    cues: ['weights hang by your sides', 'back knee kisses the floor', 'push through the front foot'],
    mistakes: ['Front knee caving in', 'Leaning to one side'] },
  { id: 'reverse-lunge', name: 'Reverse lunge', motion: 'reverseLunge', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['quads', 'glutes'], secondary: ['hamstrings', 'adductors'], camera: 'side', equipment: [], sets: '3 x 8 each side',
    cues: ['step back long', 'most of your weight in the front foot', 'push through the front heel to come back'],
    mistakes: ['Short step', 'Front knee caving', 'Wobbling side to side'] },
  { id: 'bulgarian-split-squat', name: 'Bulgarian split squat', motion: 'bulgarian', load: 'dumbbells', area: 'Legs', where: 'both', level: 2,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'hip_flexors'], camera: 'side', fault: 'knees_cave', equipment: ['Bench or couch', 'Dumbbells'], sets: '3 x 8 each side',
    cues: ['back foot laces down on the bench', 'drop straight down', 'front knee tracks over your toes'],
    mistakes: ['Front foot too close to the bench', 'Pushing off the back leg'] },
  { id: 'step-up', name: 'Step-up', motion: 'stepUp', load: 'dumbbells', area: 'Legs', where: 'home', level: 1,
    muscles: ['quads', 'glutes'], secondary: ['calves', 'hamstrings'], camera: 'side', fault: 'knees_cave', equipment: ['Step or box', 'Dumbbells (optional)'], sets: '3 x 8 each side',
    cues: ['whole foot on the box', 'drive through the top leg, not the bottom one', 'step down slowly'],
    mistakes: ['Pushing off the floor leg', 'Knee caving in on the box'] },
  { id: 'lateral-lunge', name: 'Lateral lunge', motion: 'lateralLunge', load: 'bodyweight', area: 'Legs', where: 'home', level: 2,
    muscles: ['adductors', 'glutes', 'quads'], secondary: ['hamstrings'], camera: 'front', equipment: [], sets: '3 x 6 each side',
    cues: ['sit back into one hip', 'keep the other leg long', 'both feet stay flat'],
    mistakes: ['Knee shooting past the toes', 'Rounding the back'] },
  { id: 'standing-hip-abduction', name: 'Standing hip abduction', motion: 'standingAbduction', load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['glute_med'], secondary: ['obliques'], camera: 'front', equipment: ['Wall or chair for balance'], sets: '3 x 12 each side',
    cues: ['stand tall, hold something for balance', 'lift the leg out to the side, toes forward', 'do not lean the other way'],
    mistakes: ['Leaning the torso', 'Turning the toes up'] },
  { id: 'glute-bridge', name: 'Glute bridge', motion: 'bridge', load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['glutes'], secondary: ['hamstrings', 'abs'], camera: 'side', fault: 'arch_back', equipment: ['Mat'], sets: '3 x 12',
    cues: ['squeeze your glutes to lift', 'ribs stay down', 'pause one second at the top'],
    mistakes: ['Arching the lower back', 'Pushing through the toes'] },
  { id: 'single-leg-bridge', name: 'Single-leg glute bridge', motion: 'bridge', opts: { single: true }, load: 'bodyweight', area: 'Legs', where: 'home', level: 2,
    muscles: ['glutes'], secondary: ['hamstrings', 'abs'], camera: 'side', equipment: ['Mat'], sets: '3 x 8 each side',
    cues: ['press through the heel of the bent leg', 'keep your hips level', 'lower slowly'],
    mistakes: ['Hips twisting', 'Arching the lower back'] },
  { id: 'db-rdl', name: 'Dumbbell Romanian deadlift', motion: 'hinge', opts: { kind: 'rdl' }, load: 'dumbbells', area: 'Legs', where: 'both', level: 2,
    muscles: ['hamstrings', 'glutes'], secondary: ['lower_back', 'forearms'], camera: 'side', fault: 'back_round', equipment: ['Dumbbells'], sets: '3 x 10',
    cues: ['push your hips back to a wall behind you', 'weights slide down your thighs', 'soft knees, long spine'],
    mistakes: ['Rounding the lower back', 'Squatting instead of hinging'] },
  { id: 'barbell-deadlift', name: 'Barbell deadlift', motion: 'hinge', opts: { kind: 'deadlift' }, load: 'barbell', area: 'Legs', where: 'gym', level: 3,
    muscles: ['glutes', 'hamstrings', 'lower_back'], secondary: ['quads', 'upper_back', 'forearms'], camera: 'three', fault: 'back_round', equipment: ['Barbell', 'Plates'], sets: '4 x 5',
    cues: ['bar over the middle of your foot', 'pull the slack out of the bar first', 'push the floor away'],
    mistakes: ['Lower back rounding', 'Bar drifting away from the legs', 'Jerking the bar off the floor'] },
  { id: 'kettlebell-swing', name: 'Kettlebell swing', motion: 'hinge', opts: { kind: 'swing' }, load: 'kettlebell', area: 'Legs', where: 'both', level: 2,
    muscles: ['glutes', 'hamstrings'], secondary: ['lower_back', 'abs', 'forearms'], camera: 'side', fault: 'back_round', equipment: ['Kettlebell'], sets: '4 x 15',
    cues: ['hike the bell back between your legs', 'snap your hips forward', 'arms just guide the bell'],
    mistakes: ['Squatting the swing', 'Lifting with the arms', 'Rounding the back'] },
  { id: 'single-leg-rdl', name: 'Single-leg Romanian deadlift', motion: 'singleLegRdl', load: 'dumbbells', area: 'Legs', where: 'both', level: 2,
    muscles: ['hamstrings', 'glutes'], secondary: ['glute_med', 'lower_back'], camera: 'side', fault: 'back_round', equipment: ['Dumbbells'], sets: '3 x 8 each side',
    cues: ['reach the back leg long', 'hips stay square to the floor', 'soft standing knee'],
    mistakes: ['Hip opening up', 'Rounding the back'] },
  { id: 'standing-calf-raise', name: 'Standing calf raise', motion: 'calfRaise', load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['calves'], secondary: [], camera: 'low', equipment: [], sets: '3 x 15',
    cues: ['rise high onto the big toe', 'pause at the top', 'lower slowly, three seconds down'],
    mistakes: ['Bouncing', 'Rolling onto the outside of the foot'] },
  { id: 'seated-calf-raise', name: 'Seated calf raise', motion: 'seatedCalf', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['calves'], secondary: [], camera: 'side', equipment: ['Bench or chair', 'Dumbbell'], sets: '3 x 15',
    cues: ['weight on top of your knees', 'lift the heels as high as you can', 'lower slowly'],
    mistakes: ['Rushing the reps', 'Half range'] },
  { id: 'leg-press', name: 'Leg press', motion: 'legPress', load: 'machine', area: 'Legs', where: 'gym', level: 2,
    muscles: ['quads', 'glutes'], secondary: ['adductors', 'hamstrings'], camera: 'side', fault: 'knees_cave', faultCamera: 'over', equipment: ['Leg press machine'], sets: '3 x 10',
    cues: ['feet flat, hip width', 'knees track over your toes', 'lower until your hips start to lift, then stop'],
    mistakes: ['Knees caving in', 'Lower back peeling off the pad', 'Locking the knees hard'] },
  { id: 'lying-leg-curl', name: 'Lying leg curl', motion: 'legCurl', load: 'machine', area: 'Legs', where: 'gym', level: 1,
    muscles: ['hamstrings'], secondary: ['calves'], camera: 'side', equipment: ['Leg curl machine'], sets: '3 x 12',
    cues: ['hips pressed into the pad', 'curl your heels to your glutes', 'three seconds down'],
    mistakes: ['Hips lifting off the pad', 'Swinging the weight'] },
  { id: 'leg-extension', name: 'Leg extension', motion: 'legExtension', load: 'machine', area: 'Legs', where: 'gym', level: 1,
    muscles: ['quads'], secondary: [], camera: 'side', equipment: ['Leg extension machine'], sets: '3 x 12',
    cues: ['sit all the way back', 'straighten fully and squeeze', 'lower with control'],
    mistakes: ['Kicking the weight up', 'Hips sliding forward'] },
  { id: 'seated-knee-extension', name: 'Seated knee extension', motion: 'legExtension', opts: { chair: true }, load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['quads'], secondary: [], camera: 'side', equipment: ['Chair', 'Ankle weight (optional)'], sets: '3 x 12',
    cues: ['sit tall', 'straighten the knee all the way', 'hold two seconds, lower slowly'],
    mistakes: ['Leaning back', 'Not reaching full straight'] },
  { id: 'clamshell', name: 'Clamshell', motion: 'clamshell', load: 'band', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['glute_med'], secondary: ['glutes'], camera: 'front', equipment: ['Mat', 'Mini band (optional)'], sets: '3 x 15 each side',
    cues: ['heels stay together', 'open the top knee like a book', 'do not let the top hip roll back'],
    mistakes: ['Rolling the pelvis back', 'Rushing'] },
  { id: 'side-lying-leg-raise', name: 'Side-lying leg raise', motion: 'sideLegRaise', load: 'bodyweight', area: 'Legs', where: 'home', level: 1, rehab: true,
    muscles: ['glute_med'], secondary: ['obliques'], camera: 'front', equipment: ['Mat'], sets: '3 x 12 each side',
    cues: ['lead with the heel', 'toes point forward, not up', 'lift only as high as you can without rolling'],
    mistakes: ['Toes turning up', 'Rolling backward'] },
  { id: 'band-lateral-walk', name: 'Banded lateral walk', motion: 'lateralWalk', load: 'band', area: 'Legs', where: 'home', level: 1,
    muscles: ['glute_med'], secondary: ['glutes', 'quads'], camera: 'front', fault: 'knees_cave', equipment: ['Mini band'], sets: '3 x 10 steps each way',
    cues: ['stay in a quarter squat', 'push the knees out against the band', 'small, controlled steps'],
    mistakes: ['Knees caving in', 'Standing up tall', 'Feet snapping together'] },
  { id: 'donkey-kick', name: 'Donkey kick', motion: 'donkeyKick', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['glutes'], secondary: ['hamstrings', 'abs'], camera: 'side', equipment: ['Mat'], sets: '3 x 12 each side',
    cues: ['press the foot to the ceiling', 'keep the knee bent at 90', 'back stays flat like a table'],
    mistakes: ['Arching the lower back', 'Swinging the leg'] },
  { id: 'fire-hydrant', name: 'Fire hydrant', motion: 'fireHydrant', load: 'bodyweight', area: 'Legs', where: 'home', level: 1,
    muscles: ['glute_med'], secondary: ['glutes'], camera: 'threeBack', equipment: ['Mat'], sets: '3 x 12 each side',
    cues: ['lift the knee out to the side', 'keep your weight centred', 'slow on the way down'],
    mistakes: ['Shifting weight away from the working leg', 'Twisting the spine'] },

  // ---------------- PUSH ----------------
  { id: 'push-up', name: 'Push-up', motion: 'pushup', load: 'bodyweight', area: 'Push', where: 'home', level: 2,
    muscles: ['pecs', 'triceps'], secondary: ['delts', 'abs'], camera: 'side', fault: 'hips_sag', equipment: [], sets: '3 x 10',
    cues: ['hands under your shoulders', 'body moves as one plank', 'push the floor away'],
    mistakes: ['Hips sagging', 'Elbows flaring straight out', 'Half reps'] },
  { id: 'incline-push-up', name: 'Incline push-up', motion: 'pushup', opts: { incline: true }, load: 'bodyweight', area: 'Push', where: 'home', level: 1,
    muscles: ['pecs', 'triceps'], secondary: ['delts', 'abs'], camera: 'side', fault: 'hips_sag', equipment: ['Bench, counter or sturdy chair'], sets: '3 x 12',
    cues: ['hands on the edge, shoulder width', 'chest to the bench', 'squeeze your glutes the whole time'],
    mistakes: ['Hips sagging', 'Head poking forward'] },
  { id: 'knee-push-up', name: 'Knee push-up', motion: 'pushup', opts: { knees: true }, load: 'bodyweight', area: 'Push', where: 'home', level: 1,
    muscles: ['pecs', 'triceps'], secondary: ['delts', 'abs'], camera: 'side', fault: 'hips_sag', equipment: ['Mat'], sets: '3 x 10',
    cues: ['straight line from knees to head', 'lower your chest between your hands', 'press back up'],
    mistakes: ['Hips piking up', 'Hips sagging'] },
  { id: 'pike-push-up', name: 'Pike push-up', motion: 'pikePushup', load: 'bodyweight', area: 'Push', where: 'home', level: 3,
    muscles: ['delts', 'triceps'], secondary: ['upper_back', 'pecs'], camera: 'side', equipment: ['Mat'], sets: '3 x 8',
    cues: ['hips high like an upside-down V', 'lower the top of your head toward the floor', 'press back up'],
    mistakes: ['Hips dropping', 'Elbows flaring wide'] },
  { id: 'db-bench-press', name: 'Dumbbell bench press', motion: 'benchPress', load: 'dumbbells', area: 'Push', where: 'both', level: 2,
    muscles: ['pecs', 'triceps'], secondary: ['delts'], camera: 'side', fault: 'arch_back', equipment: ['Bench', 'Dumbbells'], sets: '3 x 10',
    cues: ['feet planted, shoulder blades squeezed', 'lower to the sides of your chest', 'press up and slightly in'],
    mistakes: ['Big lower back arch', 'Dropping the weights too fast'] },
  { id: 'barbell-bench-press', name: 'Barbell bench press', motion: 'benchPress', opts: { barbell: true }, load: 'machine', area: 'Push', where: 'gym', level: 3,
    muscles: ['pecs', 'triceps'], secondary: ['delts'], camera: 'three', fault: 'arch_back', equipment: ['Bench', 'Barbell'], sets: '4 x 6',
    cues: ['eyes under the bar', 'touch the lower chest', 'drive your feet into the floor'],
    mistakes: ['Bouncing the bar', 'Butt lifting off the bench'] },
  { id: 'db-shoulder-press', name: 'Dumbbell shoulder press', motion: 'shoulderPress', load: 'dumbbells', area: 'Push', where: 'both', level: 2,
    muscles: ['delts', 'triceps'], secondary: ['upper_back', 'abs'], camera: 'front', fault: 'arch_back', equipment: ['Dumbbells'], sets: '3 x 10',
    cues: ['ribs down, glutes tight', 'press straight up', 'finish with biceps by your ears'],
    mistakes: ['Leaning back', 'Shrugging to the ears'] },
  { id: 'lateral-raise', name: 'Lateral raise', motion: 'lateralRaise', load: 'dumbbells', area: 'Push', where: 'both', level: 1,
    muscles: ['delts'], secondary: ['traps'], camera: 'front', equipment: ['Dumbbells'], sets: '3 x 12',
    cues: ['lead with the elbows', 'stop at shoulder height', 'slow on the way down'],
    mistakes: ['Swinging', 'Shrugging'] },
  { id: 'front-raise', name: 'Front raise', motion: 'frontRaise', load: 'dumbbells', area: 'Push', where: 'both', level: 1,
    muscles: ['delts'], secondary: ['pecs'], camera: 'side', equipment: ['Dumbbells'], sets: '3 x 12',
    cues: ['arms long, soft elbows', 'lift to eye level', 'no leaning back'],
    mistakes: ['Using momentum', 'Arching the back'] },
  { id: 'bench-dip', name: 'Bench dip', motion: 'benchDip', load: 'bodyweight', area: 'Push', where: 'home', level: 2,
    muscles: ['triceps'], secondary: ['pecs', 'delts'], camera: 'side', equipment: ['Bench or sturdy chair'], sets: '3 x 10',
    cues: ['hips close to the bench', 'bend the elbows straight back', 'stop when upper arms are level'],
    mistakes: ['Going too deep', 'Shoulders rolling forward'] },
  { id: 'overhead-triceps-extension', name: 'Overhead triceps extension', motion: 'overheadTriceps', load: 'goblet', area: 'Push', where: 'both', level: 1,
    muscles: ['triceps'], secondary: ['abs'], camera: 'side', equipment: ['Dumbbell'], sets: '3 x 12',
    cues: ['elbows point to the ceiling', 'lower behind your head', 'straighten fully'],
    mistakes: ['Elbows flaring', 'Arching the back'] },
  { id: 'cable-triceps-pushdown', name: 'Cable triceps pushdown', motion: 'pushdown', load: 'machine', area: 'Push', where: 'gym', level: 1,
    muscles: ['triceps'], secondary: [], camera: 'side', equipment: ['Cable machine'], sets: '3 x 12',
    cues: ['elbows pinned to your sides', 'push down until straight', 'control it back up'],
    mistakes: ['Elbows drifting forward', 'Leaning over the bar'] },
  { id: 'wall-slide', name: 'Wall slide', motion: 'wallSlide', load: 'bodyweight', area: 'Push', where: 'home', level: 1, rehab: true,
    muscles: ['upper_back', 'delts'], secondary: ['traps'], camera: 'front', equipment: ['Wall'], sets: '2 x 10',
    cues: ['back and arms against the wall', 'slide up only as far as the arms stay in contact', 'ribs stay down'],
    mistakes: ['Arching off the wall', 'Shrugging'] },

  // ---------------- PULL ----------------
  { id: 'lat-pulldown', name: 'Lat pulldown', motion: 'pulldown', load: 'machine', area: 'Pull', where: 'gym', level: 1,
    muscles: ['lats'], secondary: ['biceps', 'upper_back', 'rear_delts'], camera: 'back', fault: 'lean_back', equipment: ['Lat pulldown machine'], sets: '3 x 10',
    cues: ['pull your elbows down into your back pockets', 'bar to the top of your chest', 'control it back up'],
    mistakes: ['Leaning way back', 'Pulling with the arms only', 'Shrugging'] },
  { id: 'pull-up', name: 'Pull-up', motion: 'pullup', load: 'bodyweight', area: 'Pull', where: 'both', level: 3,
    muscles: ['lats'], secondary: ['biceps', 'upper_back', 'forearms'], camera: 'back', equipment: ['Pull-up bar'], sets: '3 x 5',
    cues: ['start from a dead hang', 'drive the elbows down', 'chin over the bar, then lower slowly'],
    mistakes: ['Kipping', 'Half reps'] },
  { id: 'bent-over-row', name: 'Bent-over dumbbell row', motion: 'bentRow', load: 'dumbbells', area: 'Pull', where: 'both', level: 2,
    muscles: ['lats', 'upper_back'], secondary: ['biceps', 'rear_delts', 'lower_back'], camera: 'side', fault: 'back_round', equipment: ['Dumbbells'], sets: '3 x 10',
    cues: ['hinge forward with a flat back', 'row the weights to your hips', 'squeeze your shoulder blades'],
    mistakes: ['Back rounding', 'Standing up as you row'] },
  { id: 'single-arm-row', name: 'Single-arm dumbbell row', motion: 'singleArmRow', load: 'none', area: 'Pull', where: 'both', level: 1,
    muscles: ['lats', 'upper_back'], secondary: ['biceps', 'rear_delts'], camera: 'sideR', equipment: ['Bench', 'Dumbbell'], sets: '3 x 10 each side',
    cues: ['hand and knee on the bench', 'pull the elbow toward your hip', 'do not twist open'],
    mistakes: ['Twisting the torso', 'Shrugging the weight up'] },
  { id: 'seated-cable-row', name: 'Seated cable row', motion: 'cableRow', load: 'machine', area: 'Pull', where: 'gym', level: 1,
    muscles: ['upper_back', 'lats'], secondary: ['biceps', 'rear_delts'], camera: 'side', fault: 'back_round', equipment: ['Cable row machine'], sets: '3 x 12',
    cues: ['sit tall', 'pull the handle to your belly button', 'shoulders back and down'],
    mistakes: ['Rocking back and forth', 'Rounding forward on the return'] },
  { id: 'band-pull-apart', name: 'Band pull-apart', motion: 'pullApart', load: 'band', area: 'Pull', where: 'home', level: 1, rehab: true,
    muscles: ['rear_delts', 'upper_back'], secondary: ['traps'], camera: 'back', equipment: ['Resistance band'], sets: '3 x 15',
    cues: ['arms straight at chest height', 'pull the band to your chest', 'squeeze between the shoulder blades'],
    mistakes: ['Shrugging', 'Bending the elbows'] },
  { id: 'face-pull', name: 'Face pull', motion: 'facePull', load: 'machine', area: 'Pull', where: 'gym', level: 2,
    muscles: ['rear_delts', 'upper_back'], secondary: ['traps'], camera: 'three', equipment: ['Cable machine', 'Rope'], sets: '3 x 15',
    cues: ['pull the rope to your forehead', 'elbows high and wide', 'finish like a double biceps pose'],
    mistakes: ['Elbows dropping', 'Leaning back'] },
  { id: 'db-biceps-curl', name: 'Dumbbell biceps curl', motion: 'curl', load: 'dumbbells', area: 'Pull', where: 'both', level: 1,
    muscles: ['biceps'], secondary: ['forearms'], camera: 'three', equipment: ['Dumbbells'], sets: '3 x 12',
    cues: ['elbows stay by your sides', 'curl all the way up', 'three seconds down'],
    mistakes: ['Swinging the body', 'Elbows drifting forward'] },
  { id: 'hammer-curl', name: 'Hammer curl', motion: 'curl', load: 'dumbbellsNeutral', area: 'Pull', where: 'both', level: 1,
    muscles: ['biceps', 'forearms'], secondary: [], camera: 'three', equipment: ['Dumbbells'], sets: '3 x 12',
    cues: ['thumbs up the whole time', 'elbows still', 'slow down'],
    mistakes: ['Swinging', 'Short range'] },
  { id: 'reverse-fly', name: 'Bent-over reverse fly', motion: 'reverseFly', load: 'dumbbells', area: 'Pull', where: 'both', level: 1,
    muscles: ['rear_delts', 'upper_back'], secondary: ['traps'], camera: 'back', equipment: ['Light dumbbells'], sets: '3 x 12',
    cues: ['hinge forward, flat back', 'open the arms like wings', 'lead with the pinkies'],
    mistakes: ['Using heavy weights and swinging', 'Rounding the back'] },
  { id: 'superman', name: 'Superman', motion: 'superman', load: 'bodyweight', area: 'Pull', where: 'home', level: 1,
    muscles: ['lower_back', 'glutes'], secondary: ['upper_back', 'hamstrings'], camera: 'side', equipment: ['Mat'], sets: '3 x 10',
    cues: ['lift arms and legs a few inches', 'look at the floor', 'hold two seconds'],
    mistakes: ['Cranking the neck up', 'Lifting too high'] },

  // ---------------- CORE ----------------
  { id: 'plank', name: 'Forearm plank', motion: 'plank', load: 'bodyweight', area: 'Core', where: 'home', level: 1,
    muscles: ['abs'], secondary: ['obliques', 'delts', 'glutes'], camera: 'side', fault: 'hips_sag', equipment: ['Mat'], sets: '3 x 30 sec',
    cues: ['elbows under shoulders', 'squeeze glutes and pull ribs down', 'breathe while you hold'],
    mistakes: ['Hips sagging', 'Hips piked up', 'Holding the breath'] },
  { id: 'side-plank', name: 'Side plank', motion: 'sidePlank', load: 'bodyweight', area: 'Core', where: 'home', level: 2,
    muscles: ['obliques'], secondary: ['glute_med', 'abs', 'delts'], camera: 'front', equipment: ['Mat'], sets: '3 x 20 sec each side',
    cues: ['elbow under the shoulder', 'lift the hips high', 'straight line from head to feet'],
    mistakes: ['Hips dropping', 'Rolling forward'] },
  { id: 'dead-bug', name: 'Dead bug', motion: 'deadBug', load: 'bodyweight', area: 'Core', where: 'home', level: 1, rehab: true,
    muscles: ['abs'], secondary: ['obliques', 'hip_flexors'], camera: 'side', fault: 'arch_back', equipment: ['Mat'], sets: '3 x 6 each side',
    cues: ['press your lower back into the floor', 'reach opposite arm and leg long', 'breathe out as you reach'],
    mistakes: ['Lower back arching', 'Moving too fast'] },
  { id: 'bird-dog', name: 'Bird dog', motion: 'birdDog', load: 'bodyweight', area: 'Core', where: 'home', level: 1, rehab: true,
    muscles: ['lower_back', 'glutes'], secondary: ['abs', 'delts'], camera: 'side', fault: 'arch_back', equipment: ['Mat'], sets: '3 x 6 each side',
    cues: ['reach long, not high', 'keep a cup of water balanced on your back', 'pause at full reach'],
    mistakes: ['Arching the back', 'Hips rotating'] },
  { id: 'crunch', name: 'Crunch', motion: 'crunch', load: 'bodyweight', area: 'Core', where: 'home', level: 1,
    muscles: ['abs'], secondary: ['obliques'], camera: 'side', equipment: ['Mat'], sets: '3 x 15',
    cues: ['curl your ribs toward your hips', 'lift only your shoulder blades', 'slow on the way down'],
    mistakes: ['Pulling on the neck', 'Sitting all the way up'] },
  { id: 'lying-leg-raise', name: 'Lying leg raise', motion: 'legRaise', load: 'bodyweight', area: 'Core', where: 'home', level: 2,
    muscles: ['abs', 'hip_flexors'], secondary: ['obliques'], camera: 'side', fault: 'arch_back', equipment: ['Mat'], sets: '3 x 10',
    cues: ['lower back stays glued down', 'lower the legs only as far as you can control', 'lift with the belly'],
    mistakes: ['Back arching off the floor', 'Dropping the legs'] },
  { id: 'russian-twist', name: 'Russian twist', motion: 'russianTwist', load: 'bodyweight', area: 'Core', where: 'home', level: 2,
    muscles: ['obliques'], secondary: ['abs', 'hip_flexors'], camera: 'front', equipment: ['Mat', 'Weight (optional)'], sets: '3 x 10 each side',
    cues: ['lean back with a long spine', 'turn from your ribs, not your arms', 'move slow'],
    mistakes: ['Rounding the back', 'Only moving the arms'] },
  { id: 'mountain-climber', name: 'Mountain climber', motion: 'mountainClimber', load: 'bodyweight', area: 'Core', where: 'home', level: 2,
    muscles: ['abs', 'hip_flexors'], secondary: ['delts', 'quads'], camera: 'side', equipment: ['Mat'], sets: '3 x 30 sec',
    cues: ['shoulders over hands', 'drive the knees to the chest', 'hips stay low'],
    mistakes: ['Hips bouncing high', 'Shoulders drifting back'] },
  { id: 'pallof-press', name: 'Pallof press', motion: 'pallof', load: 'band', area: 'Core', where: 'both', level: 1, rehab: true,
    muscles: ['obliques', 'abs'], secondary: ['glutes'], camera: 'front', equipment: ['Resistance band or cable'], sets: '3 x 10 each side',
    cues: ['stand side-on to the anchor', 'press straight out from your chest', 'do not let the band turn you'],
    mistakes: ['Twisting toward the anchor', 'Leaning away'] },

  // ---------------- MOBILITY & CARRIES ----------------
  { id: 'cat-cow', name: 'Cat-cow', motion: 'catCow', load: 'bodyweight', area: 'Mobility', where: 'home', level: 1, rehab: true,
    muscles: ['lower_back', 'abs'], secondary: ['upper_back'], camera: 'side', equipment: ['Mat'], sets: '2 x 8 slow',
    cues: ['round up through the whole spine', 'then let the belly sink and look up', 'move with your breath'],
    mistakes: ['Only moving the neck', 'Rushing'] },
  { id: 'half-kneeling-hip-flexor-stretch', name: 'Half-kneeling hip flexor stretch', motion: 'hipFlexorStretch', load: 'bodyweight', area: 'Mobility', where: 'home', level: 1, rehab: true,
    muscles: ['hip_flexors'], secondary: ['glutes', 'abs'], camera: 'side', equipment: ['Mat or cushion'], sets: '2 x 30 sec each side',
    cues: ['tuck your tailbone under', 'squeeze the glute of the back leg', 'shift forward gently and reach up'],
    mistakes: ['Arching the lower back', 'Lunging too far forward'] },
  { id: 'farmers-march', name: "Farmer's march", motion: 'farmerMarch', load: 'dumbbells', area: 'Mobility', where: 'both', level: 1,
    muscles: ['forearms', 'traps', 'abs'], secondary: ['glute_med', 'hip_flexors'], camera: 'front', equipment: ['Dumbbells or kettlebells'], sets: '3 x 30 sec',
    cues: ['stand tall with heavy weights', 'lift each knee to hip height', 'do not lean side to side'],
    mistakes: ['Leaning', 'Shrugging'] },
];
